### ISSUE TITLE
Installable via PyPI

### ISSUE THREAD

**Issue by cvng** [mrts/django-admin-list-filter-dropdown#1]
Do you plan to package this app so we can install it via `pip`? I can help in the proces if needed ;)

**Comment by mrts** [comment]
It already is installable with `pip` :):

``` sh
pip install git+http://github.com/mrts/django-admin-list-filter-dropdown.git
```

But you probably mean publishing to PyPI. I don't have a PyPI account yet and I don't have time for this at the moment, but yes, it's would be a good thing to do... maybe eventually, let's keep the ticket open and let's see how many votes this gets.

**Comment by cvng** [comment]
Yes you're right I meant available on PyPI :)

**Comment by andriisoldatenko** [comment]
@mrts Do you need help to release it to pypi?

**Comment by mrts** [comment]
@andriisoldatenko, thanks for the kind offer :)! Yes, if you could do it, I would be much obliged.

**Comment by axsapronov** [comment]
You can use this tutorial for it http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by mrts** [comment]
@WarmongeR1, thanks, I have seen the instructions before. It's just that it will take quite a bit of time and there already is a decent way to consume the package with `pip install git+http://...`.

But I clearly see that I need to reconsider and Just Do It taking into account the amount of interest :). Let's see how far I get right now.

**Comment by mrts** [comment]
@WarmongeR1, many thanks for the instructions, they were really to the point and helped me. I've seen longer, more convoluted and not GitHub-enhanced instructions before, hence my somewhat unjustified reluctance to deal with it :). Anyhow, all is well that ends well - **the package is uploaded to PyPI now** and README updated correspondingly, enjoy 🎉!

(The only nuisance I faced was converting Markdown to reStructuredText, did this: https://coderwall.com/p/qawuyq/use-markdown-readme-s-in-python-modules)

**Comment by mrts** [comment]
And thanks to @cvng for bringing this up in the first place :)!
