### ISSUE TITLE
PyPI version doesn't contain RelatedOnlyDropdownFilter

### ISSUE THREAD

**Issue by samuller** [mrts/django-admin-list-filter-dropdown#11]
It seems the `RelatedOnlyDropdownFilter` option was added on 15 Nov, 2017 (bc40316), but the newest [PyPI](https://pypi.org/project/django-admin-list-filter-dropdown/#history) version is from 4 May, 2017.

Could the PyPI version be updated?

**Comment by mrts** [comment]
Right you are, I'll put that on my todo list.

**Comment by adonig** [comment]
In the meantime you can fork this repository and use

`pip install git+https://github.com/<your_github_username>/django-admin-list-filter-dropdown.git`

to install it manually, or add the following to your requirements.txt

`-e git://github.com/<your_github_username>/django-admin-list-filter-dropdown.git#egg=django-admin-list-filter-dropdown`

**Comment by mrts** [comment]
The PyPI version is now updated, v1.0.2 contains RelatedOnlyDropdownFilter. Thanks for the heads-up and sorry for the long delay in getting it out!
