### ISSUE TITLE
BooleanField filter as a dropdown too

### ISSUE THREAD

**Issue by moccand** [mrts/django-admin-list-filter-dropdown#24]
BooleanField are not shown as a dropdown.
Am I doing wrong ?

my model : 
    visible = models.BooleanField(blank=True, null=True)

my admin : 
list_filter = [ ('visible', DropdownFilter),]

**Comment by mrts** [comment]
Currently the filter appears only when there are more than 3 choices:
https://github.com/mrts/django-admin-list-filter-dropdown/blob/master/django_admin_listfilter_dropdown/templates/django_admin_listfilter_dropdown/dropdown_filter.html#L5

So, you are not doing anything wrong, this is intended behaviour.
