### ISSUE TITLE
how to specify the length at which the dropwdown filter will be activated?

### ISSUE THREAD

**Issue by luisjdtt** [mrts/django-admin-list-filter-dropdown#25]
I'm using a ChoiceDropDownFilter that only has 3 options for filtering  and the dropdown is therefore not activated. I know they are just three elements but i need them to be in the dropdown. Is there a way to specify the length at which the dropdown filter will be activated? What possible course of action should i pursue?

**Comment by seancallaway** [comment]
It looks like it's hard coded in [the template](https://github.com/mrts/django-admin-list-filter-dropdown/blob/8ab1575dcd3cb9b28a80cc07695cec65fa85dfad/django_admin_listfilter_dropdown/templates/django_admin_listfilter_dropdown/dropdown_filter.html#L5). You could probably override the template.

**Comment by luisjdtt** [comment]
Thank you! It worked.

**Comment by mrts** [comment]
There's actually a pull request to make it configurable, but it needs amending: https://github.com/mrts/django-admin-list-filter-dropdown/pull/14
