### ISSUE TITLE
I am using Django 4.2 not able to get the DropDown FIlter

### ISSUE THREAD

**Issue by fossbalaji** [mrts/django-admin-list-filter-dropdown#26]
I have followed all the steps, still seeing the old list filter istead of dropdown filter 

The support has been stopped?

**Comment by mrts** [comment]
Thanks for the report! I will check with Django 4.2 and will let you know.

**Comment by AhmedKamal20** [comment]
How many choices do you have for this filter? if it's less than four, it will not show the dropdown
I don't know the reason, and it confused me until I discovered it 

https://github.com/mrts/django-admin-list-filter-dropdown/blob/8ab1575dcd3cb9b28a80cc07695cec65fa85dfad/django_admin_listfilter_dropdown/templates/django_admin_listfilter_dropdown/dropdown_filter.html#L5

**Comment by mrts** [comment]
@AhmedKamal20, thanks for pointing this out, this is probably the case. Do you care to send a patch to the README to get it documented?

**Comment by mrts** [comment]
Closing, @fossbalaji, feel free to reopen if it doesn't work with more than 4 values.

**Comment by AhmedKamal20** [comment]
@mrts Sure
Here it's is https://github.com/mrts/django-admin-list-filter-dropdown/pull/27
