### ISSUE TITLE
min threshold

### ISSUE THREAD

**Issue by TZanke** [mrts/django-admin-list-filter-dropdown#3]
Is it possible to add a threshold? So if the threshold is not reached, the list is displayed as django default?

Reason:
Some Customers have 100 Objects, here the dropdown saves a lot of space. But others only have 5, where the Dropdown slows down the user.

**Comment by mrts** [comment]
There already is a threshold of "more than 4" to trigger the dropdown, see [this line in the template](https://github.com/mrts/django-admin-list-filter-dropdown/blob/master/django_admin_listfilter_dropdown/templates/django_admin_listfilter_dropdown/dropdown_filter.html#L5). Does this satisfy your requirements?

**Comment by TZanke** [comment]
Nice. Never noticed it because there are always more then 4. For my use case, and a FullHD screen, i would prefer 10, but atm this is not a critical improvement.

Will keep this in mind if i need it customizeable.

**Comment by mrts** [comment]
OK, I will close this for now then. Please reopen if you think customization is important (and I would happily accept a pull request 😉).

**Comment by beebek** [comment]
Feature to customize the threshold value from settings would be great.

**Comment by mrts** [comment]
@beebek, pull requests welcome 😉
