### ISSUE TITLE
Cannot inherit from FieldListFilter

### ISSUE THREAD

**Issue by jonathanchin** [mrts/django-admin-list-filter-dropdown#5]
Using this package (any of the filters) I get this error: "(admin.E114) The value of 'list_filter[1]' must not inherit from 'FieldListFilter'."  Seems like Django doesn't want us mucking with internals.  Is there a workaround to avoid the error?  I'm using Django 1.11.

**Comment by mrts** [comment]
I will investigate this eventually, meanwhile any help is much appreciated.

**Comment by mrts** [comment]
@jonathanchin I cannot reproduce this, please share a code snippet and feel free to reopen.

**Comment by szabozoltan69** [comment]
I had similar issue, in my case it was a typo. I wrote:
list_filter   = ('sg', ChoiceDropdownFilter)
instead of the correct
list_filter   = (('sg', ChoiceDropdownFilter),)

**Comment by nitishsainani** [comment]
`list_filter = ('date', DateRangeFilter)` wrong 👎 
`list_filter = (('date', DateRangeFilter))` wrong 👎 
`list_filter = (('date', DateRangeFilter),)` right 👍
