### ISSUE TITLE
For CharField with choices, the filter shows the "short name" of the choice instead of the verbose name

### ISSUE THREAD

**Issue by jcmcken** [mrts/django-admin-list-filter-dropdown#9]
In the default Django filter, the verbose name is shown when a ``CharField`` filter has ``choices``. When I enable your filter classes, I only get the short name, which isn't really recognizable or useful for filtering.

**Comment by mrts** [comment]
Hm, I haven't tried that myself. What version of Django are you using?

**Comment by jcmcken** [comment]
```pycon
>>> import django
>>> django.__version__
'2.0.4'
```

Typically if ``somefield`` is the field, you would use the ``get_somefield_display`` helper method that Django provides, which automatically converts the short form of the choice to the long form

**Comment by mrts** [comment]
Are you using `ChoiceDropdownFilter`?

In case you are and it still does not work:

My assumption would be that `{{ choice.display }}` will take care of this in the template layer as that's what Django's admin and FeinCMS use. But perhaps things have changed. Do you care to investigate this a bit? If yes, take a look at the following:
- how does Django's own `templates/admin/filter.html` do this nowadays?
- what has changed int Django's `ChoicesFieldListFilter` that `ChoiceDropdownFilter`?

**Comment by mrts** [comment]
@jcmcken, assuming you were not using `ChoiceDropdowFilter`, closing. Please feel free to reopen if this is not the case.
